### ISSUE TITLE
shitty unlock rate

### ISSUE THREAD

**Issue by seltoxx** [Sysys242/Discord-Token-Generator#1]
bc of my proxies or?

**Comment by mesutbarzani** [comment]
do i need an http proxy or socks for generator 
![image (1)](https://github.com/Sysys242/Discord-Token-Generator/assets/137205351/f799c0e2-a4a1-4bb8-aa2e-2444bf97eba8)

**Comment by seltoxx** [comment]
> 

http

**Comment by mesutbarzani** [comment]
> > 
> 
> http

okey but how can I fix this problem 
![image (1)](https://github.com/Sysys242/Discord-Token-Generator/assets/137205351/a49fbb58-09a9-47bf-ad57-1774b46663f6)
