### ISSUE TITLE
after starting it gets stuck

### ISSUE THREAD

**Issue by FelekDev** [Sysys242/Discord-Token-Generator#3]
![image](https://github.com/Sysys242/Discord-Token-Generator/assets/136157602/367cdcc5-8ed0-422d-bde5-87e887979454)
i have paid rpcxies, key etc

**Comment by FelekDev** [comment]
nvm it wasnt stuck so long after sime time i got err HTTPSConnectionPool(host='api.capsolver.com', port=443): Max retries exceeded with url: /createTask (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000276669EC150>: Failed to establish a new connection:

**Comment by Sysys242** [comment]
Capsolver down or you can't access it ( like you have debuger like http debuger opened )
